### ISSUE TITLE
Is this vim port still under active development? 

### ISSUE THREAD

**Issue by adityamwagh** [uloco/vim-bluloco-dark#1]
There hasn't been an update since a long time. However, the theme works with no problems, except there's no support for vim lightline.

Could you provide some clarification?

**Comment by uloco** [comment]
I am not actively working on this, since I have given up on customizing my vim. I don't know exactly what lightline support is, can you elaborate?

**Comment by adityamwagh** [comment]
It's a vim statusline plugin which shows the current vim mode, filename, etc - https://github.com/itchyny/lightline.vim. It's very popular and a lot of themes support lightline so that vim window looks consistent.

Anyways, if you aren't working on the vim port, should I fork and continue the development from here on?

Very nice theme BTW. Thanks for making it.

**Comment by uloco** [comment]
I am planning to introduce a webpage, where we can manage all the different platforms / editors like dracula did. There should be a github org also. But right now I do not have time to continue work on other platforms. I am only using vscode with the vim plugin myself. I'd much rather appreciate though if you fork and just make a pull request with the changes. If you really want to continue developing this further maybe we can decide to move everything to a org together. What do you think?

I don't think that other people really understand my rationale behind why I chose what color in which place yet (see: https://github.com/uloco/theme-bluloco-light/issues/13#issuecomment-572978986).

**Comment by adityamwagh** [comment]
That's awesome! I would definitely be helping you with this. Moving it to an org is a very neat idea. It would keep everything in one place. 

I don't have much experience with vim and vimscript, but I will see what others have done, and try to make changes accordingly. I also understand the problem with colors since you've decided colors as per the filetype. I guess this would need to be done for as many types as possible.

**Comment by uloco** [comment]
See https://github.com/uloco/bluloco.nvim, although I am only supporting Lualine for now. Will add support soon.
